"""Golden-move regression: the optimized pursuit search must reproduce the
PRE-optimization engine's chosen actions move-for-move (fixture generated by the
un-cached engine, 2026-08-14, fixed depth + unbounded budget = deterministic).

Full corpus (540 actions across depths 2-4) verified at optimization time with
zero mismatches and a 10.3x speedup; CI re-checks a fast representative subset.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from cop_worker.rl.pursuit_search import best_cop_action, best_thief_action

_FIXTURE = Path(__file__).parent / "fixtures" / "pursuit_golden.json"
_CASES = json.loads(_FIXTURE.read_text(encoding="utf-8"))["cases"]


@pytest.mark.parametrize("idx", range(0, 120, 4))  # every 4th case: 30 cases, fast
def test_depth3_actions_match_golden(idx):
    c = _CASES[idx]
    barriers = set(map(tuple, c["barriers"]))
    assert (
        best_cop_action(
            tuple(c["cop"]),
            tuple(c["thief"]),
            barriers,
            c["barriers_left"],
            c["steps_left"],
            depth=3,
            time_budget_s=1e9,
        )
        == c["cop_d3"]
    )
    assert (
        best_thief_action(
            tuple(c["cop"]),
            tuple(c["thief"]),
            barriers,
            c["steps_left"],
            depth=3,
            cop_barriers_left=c["barriers_left"],
            time_budget_s=1e9,
        )
        == c["thief_d3"]
    )


@pytest.mark.parametrize("idx", range(0, 30, 3))  # depth-4 spot checks
def test_depth4_actions_match_golden(idx):
    c = _CASES[idx]
    if "cop_d4" not in c:
        pytest.skip("no d4 golden for this case")
    barriers = set(map(tuple, c["barriers"]))
    assert (
        best_cop_action(
            tuple(c["cop"]),
            tuple(c["thief"]),
            barriers,
            c["barriers_left"],
            c["steps_left"],
            depth=4,
            time_budget_s=1e9,
        )
        == c["cop_d4"]
    )
