"""Per-root memoization for the pursuit search — exact-equivalence speedups only.

The search's cost is thousands of BFS flood-fills over a handful of DISTINCT
(source, barrier-set) pairs. Caching the distance maps returns bit-identical
values, so the chosen moves cannot change (pinned by the golden corpus in
tests/fixtures/pursuit_golden.json, generated by the pre-optimization engine).
The cache is cleared at every search root: bounded memory, no staleness.
"""

from __future__ import annotations

from cop_worker.rl.pursuit_eval import _dist_map

_DIST: dict = {}


def reset() -> None:
    _DIST.clear()


def dist_map(src, barriers, n) -> dict:
    """Memoized _dist_map keyed on (src, frozen barrier set, n) — bit-identical."""
    key = (src, frozenset(barriers), n)
    cached = _DIST.get(key)
    if cached is None:
        cached = _dist_map(src, barriers, n)
        _DIST[key] = cached
    return cached


def evaluate_cached(cop, thief, barriers, n, steps_left) -> float:
    """pursuit_eval.evaluate computed from cached maps — identical arithmetic.

    dist(cop→thief) == dist_map(cop)[thief] (same BFS, layered order), with the
    same 2*n*n unreachable fallback; territory is the same comprehension over
    the two maps. Weights unchanged (40/16/2 — see pursuit_eval.evaluate).
    """
    cd = dist_map(cop, barriers, n)
    td = dist_map(thief, barriers, n)
    dist = cd.get(thief, 2 * n * n)
    territory = sum(1 for cell, d in td.items() if d < cd.get(cell, 10_000))
    return -40.0 * dist - 16.0 * territory + 2.0 * (35 - steps_left)
