"""Compatibility shim — all implementation lives in cop_worker.protocol.reference_v3."""

from cop_worker.protocol.reference_v3 import *  # noqa: F401,F403
from cop_worker.protocol.reference_v3 import (  # noqa: F401
    REFERENCE_V3_DIALECT,
    REFERENCE_V3_SCENT_LOCK,
    REFERENCE_V3_TOOLS,
    REFERENCE_V3_WIRE_LOCK,
    TERMS_KEYS,
    NegotiatedReferenceV3,
    ReferenceV3EquivocationError,
    ReferenceV3Error,
    ReferenceV3Inbox,
    ReferenceV3Profile,
    ReferenceV3Session,
    assert_core_vectors,
    build_negotiation,
    build_turn,
    canonical_hash,
    canonical_json,
    default_terms,
    derive_game_id,
    derive_game_uid,
    is_reference_v3_surface,
    reference_commit,
    register_reference_v3_tools,
    terms_signature,
    validate_turn,
    verify_audit,
    verify_negotiation,
)
